version: "3.7"
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ./redis/data:/data/redis
      - ./redis/logs:/var/log/redis
    environment:
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/logs:/var/log/mongodb
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_DBNAME}
  api:
    build: .
    container_name: api
    ports:
      - "7100:7100"
      - "7101:7101"
    restart: always
    volumes:
      - ./main:/home/app
      - /home/app/node_modules
    command: yarn start:docker
    depends_on:
      - mongodb
      - redis
    environment:
      APP_NAME: ${APP_NAME}
      PORT: ${PORT}
      SOCKET_PORT: ${SOCKET_PORT}
      SOCKET_ORIGIN: ${SOCKET_ORIGIN}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_HOST: ${REDIS_HOST}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DBNAME: ${MONGO_DBNAME}
      MONGO_CONNECT: ${MONGO_CONNECT}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
